package com.xomorod.location.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATION".
 */
public class Location {

    private Long id;
    private String Latitude;
    private String Longitude;
    private String Accuracy;
    private String LocationName;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, String Latitude, String Longitude, String Accuracy, String LocationName) {
        this.id = id;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.Accuracy = Accuracy;
        this.LocationName = LocationName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    public String getAccuracy() {
        return Accuracy;
    }

    public void setAccuracy(String Accuracy) {
        this.Accuracy = Accuracy;
    }

    public String getLocationName() {
        return LocationName;
    }

    public void setLocationName(String LocationName) {
        this.LocationName = LocationName;
    }

}
